project_name: DOAJ
base_dir: .
# source_url: defined at run-time
exclude:
  - "*.pyc"
  - "*.png"
  - "*.gif"
  - "*.jpg"
  - "*.ico"
  - "*.jpeg"
  - "*.env"
  - "*.pdf"
  - "*.zip"
  - ".gitignore"
  - ".gitmodules"
  - ".python-version"
  - ".pytest_cache/*"
  - "*.svg"
  - "cms/data/frontmatter.yml"
  - "data_import_settings/*.json"
  - "deploy/_legacy/*"
  - "dev.cfg"
  - "doajtest/matrices/*"
  - "docs/data_models/*.txt"
  - "docs/featuremap/*"
  - "history/history.json"
  - "requirements.txt"
  - "production.cfg"
  - "test.cfg"
  - "setup.py"
#include:
exclude_dirs:
  - portality/static/crossref
  - portality/static/vendor
  - portality/static/js/vendors
  - portality/static/widget/fqw_dependencies
  - portality/migrate
  - docs/generated
  - cms/fragments
  - cms/sass
  - failed_articles
  - history
  - local_store
  - reapp_csvs
  - upload
  - .git
  - .idea
  - cms/assets/img
  - doaj.egg-info
ignore_parse_errors:
  - noop
delimiter: ~~
types: docs/featuremap/types.csv
type_validation: error
terminals: docs/featuremap/terminals.csv
# out_dir: to be specified at run-time
serialisers:
  - class: featuremap.jsonserialiser.JSONSerialiser
    dir: json
  - class: featuremap.csvserialiser.CSVSerialiser
    dir: csv
  - class: featuremap.htmlserialiser.HTMLSerialiser
    dir: html